#!/usr/bin/bash
# get paths for scripts, the repo parent dir and app name
SD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APP="$(basename $SD)"
RD="$(dirname "$SD")"
PASSWORD=creator
echo $PASSWORD>$RD/$APP.passwd
cp -rfpu $RD/debian /var/lib/machines/$APP
mkdir -p /var/lib/machines/$APP/app
cp $SD/nspawn /etc/systemd/nspawn/$APP.nspawn
mkdir -p /srv/strfry
cp $SD/strfrycheck.service /var/lib/machines/$APP/lib/systemd/system/strfrycheck.service
cp $SD/strfrycheck.timer /var/lib/machines/$APP/lib/systemd/system/strfrycheck.timer
systemd-nspawn --pipe -q -D /var/lib/machines/$APP /usr/bin/bash << EOF
	export PATH=/usr/local/go/bin:$PATH
	echo -e "$PASSWORD\n$PASSWORD" | passwd
	echo "$APP">/etc/hostname
	apt update
	apt -y install --no-install-suggests git build-essential \
		git g++ make pkg-config libtool ca-certificates \
   		libyaml-perl libtemplate-perl libregexp-grammars-perl libssl-dev \
		zlib1g-dev liblmdb-dev libflatbuffers-dev libsecp256k1-dev libzstd-dev
	git clone https://github.com/hoytech/strfry.git /app
	cd /app
    git checkout tags/0.9.6
	git submodule update --init
	make setup-golpe
	make
	# build and install cookiecutter
	git clone https://github.com/relaytools/cookiecutter.git /cookiecutter
	cd /cookiecutter
	go build -x
	cp cookiecutter /usr/local/bin
    git clone https://github.com/relaytools/spamblaster.git /spamblaster
    cd /spamblaster
    go build -x
    cp spamblaster /usr/local/bin
    git clone https://github.com/relaytools/interceptor.git /interceptor
    cd /interceptor
    go build -x
    cp interceptor /usr/local/bin
	mkdir -p /srv/strfry
	systemctl enable strfrycheck.timer
EOF
systemctl stop systemd-nspawn@$APP
