#!/usr/bin/bash
# get paths for scripts, the repo parent dir and app name
SD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APP="$(basename $SD)"
RD="$(dirname "$SD")"
PASSWORD=$(cat /dev/urandom | tr -dc 0-9a-zA-Z | head -c32)
echo $PASSWORD>$RD/$APP.passwd
cp -rfpu $RD/debian /var/lib/machines/$APP
mkdir -p /var/lib/machines/$APP/app
mkdir -p /srv/relaycreator
cp $SD/nspawn /etc/systemd/nspawn/$APP.nspawn
cp $SD/app.service /var/lib/machines/$APP/lib/systemd/system/app.service
cp $SD/deploy.service /var/lib/machines/$APP/lib/systemd/system/deploy.service
cp $SD/deploy.timer /var/lib/machines/$APP/lib/systemd/system/deploy.timer
cp $SD/deploy.sh /var/lib/machines/$APP/usr/local/bin/deploy.sh
mkdir /srv/$APP
systemd-nspawn --pipe -q -D /var/lib/machines/$APP /usr/bin/bash << EOF
	export PATH=/usr/local/go/bin:$PATH
	echo -e "$PASSWORD\n$PASSWORD" | passwd
	echo "$APP">/etc/hostname
	apt update
	apt -y install git nodejs npm --no-install-suggests
	cd /app
	git clone https://github.com/relaytools/relaycreator.git /app
	npm install
	npm run build
	systemctl enable app
	systemctl enable deploy.timer
EOF
systemctl stop systemd-nspawn@$APP
