#!/usr/bin/bash
# get paths for scripts, the repo parent dir and app name
SD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APP="$(basename $SD)"
RD="$(dirname "$SD")"
PASSWORD=creator
echo $PASSWORD>$RD/$APP.passwd
cp -rfpu $RD/debian /var/lib/machines/$APP
mkdir /var/lib/machines/$APP/app
cp $SD/nspawn /etc/systemd/nspawn/$APP.nspawn
cp $SD/haproxycheck.service /var/lib/machines/$APP/lib/systemd/system/haproxycheck.service
cp $SD/haproxycheck.timer /var/lib/machines/$APP/lib/systemd/system/haproxycheck.timer
cp -r $SD/skel/* /srv/haproxy
mkdir -p /srv/haproxy
systemd-nspawn --pipe -q -D /var/lib/machines/$APP /usr/bin/bash << EOF
	. /etc/bash.bashrc
	echo -e "$PASSWORD\n$PASSWORD" | passwd
	echo "$APP">/etc/hostname

	apt update
	apt -y install --no-install-suggests git certbot gpg curl

	curl https://haproxy.debian.net/bernat.debian.org.gpg | gpg --dearmor > /usr/share/keyrings/haproxy.debian.net.gpg
	echo deb "[signed-by=/usr/share/keyrings/haproxy.debian.net.gpg]" http://haproxy.debian.net bookworm-backports-2.8 main > /etc/apt/sources.list.d/haproxy.list
	
	apt update
	apt -y install haproxy=2.8.\*

	# build and install cookiecutter
	git clone https://github.com/relaytools/cookiecutter.git /app
	cd /app
	/usr/local/go/bin/go build
	cp cookiecutter /usr/local/bin/cookiecutter
	systemctl enable haproxycheck.timer
EOF
systemctl stop systemd-nspawn@$APP
