#!/usr/bin/bash
# get paths for script
SD=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
rm -rf $SD/debian.tar.xz $SD/debian $SD/.passwd
for i in haproxy mysql strfry relaycreator
do
	$SD/$i/stop
	$SD/$i/clean
done
